### ISSUE TITLE
[bug] drag preview node weird when using `React.StrictMode`

### ISSUE THREAD

**Issue by percy507** [minop1205/react-dnd-treeview#107] opened 2022-04-05 09:32 UTC
Hi,

Thanks for your work. It's really awesome. 

I search lots of react tree components and finally decide use yours.👍

I am use the newest version of react: v18.0.0. 

During testing, I find a weird thing in drag preview node.

> I am use the fork of [your official case](https://codesandbox.io/s/add-delete-copy-ts-owgqb?file=/src/App.tsx) locally. 
> 
> And I am use `React.StrictMode` as root component. And....I find if remove the strict mode, below behavior will not happened. 
> Hint: don't test in CodeSandbox, because it always in production, so the strict mode will not work.

![2022-04-05 17 01 31](https://user-images.githubusercontent.com/18365078/161721843-0a9fb873-a8b1-43e8-a1bb-c36bd110dec8.gif)

**Comment by minop1205** [comment] 2022-04-06 03:44
@percy507  Thanks for the bug report!

We will be releasing version 2 in the near future and will try to include the bug fixes you reported.

Please wait for a while for the official release.

**Comment by percy507** [comment] 2022-04-06 03:46
Thanks.

**Comment by percy507** [comment] 2022-04-06 10:14
@minop1205 
Here is a suggest. Enable [the official eslint plugin of react hooks](https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks) may helpful.

**Comment by percy507** [comment] 2022-04-06 14:03
@minop1205 I think I fix the problem by adding the missed deps in react hooks.😂

Here is the PR. 

https://github.com/minop1205/react-dnd-treeview/pull/108

**Comment by minop1205** [comment] 2022-04-11 06:58
@percy507 I have tried to confirm this problem locally, but have not been able to reproduce it.

Could you please tell me more about how to reproduce it?
Alternatively, a reproducible repository would be helpful.

**Comment by percy507** [comment] 2022-04-11 07:17
Which react version you are using?  Mine is the newest verison: v18.

> And I think the problem happens may because of [the new features of React.StrictMode](https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors) in v18.

You can test it again. If failed reproduce again, please send me your local test-project. (percymong@163.com)

**Comment by minop1205** [comment] 2022-04-15 08:36
Thank you for your contribute!

Merged: https://github.com/minop1205/react-dnd-treeview/pull/108

**Closed as completed** 2022-04-15 08:36 UTC
Labels: bug

**Comment by minop1205** [comment] 2022-04-15 08:38
BTW, the reason I could not reproduce this was because I was not using `createRoot` and was running in React v17 mode.

When I used `createRoot`, I was able to reproduce it.

**Comment by percy507** [comment] 2022-04-15 08:44
That's right.
