### ISSUE TITLE
Multiple trees with manual sort

### ISSUE THREAD

**Issue by dimitriiy** [minop1205/react-dnd-treeview#199] opened 2023-04-14 21:24 UTC
Hello. Thank you for your work. 

Can two trees be used with manual sorting?
I couldn't do it now.

**Comment by minop1205** [comment] 2023-04-14 23:03
@dimitriiy 
It does not work well now due to the following defects
I plan to address them with high priority.
https://github.com/minop1205/react-dnd-treeview/issues/185

Sorry, but I'm going to close this one because the Issue is duplicated.

**Closed as completed by minop1205** 2023-04-14 23:03 UTC
Labels: bug, duplicate
